{
  "formatVersion": "1.1",
  "component": {
    "group": "com.refsuite.ryft",
    "module": "ryft-android",
    "version": "2.0.2-refsuite.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.refsuite.ryft",
          "module": "ryft-core",
          "version": {
            "requires": "2.0.2-refsuite.2"
          }
        },
        {
          "group": "com.refsuite.ryft",
          "module": "ryft-ui",
          "version": {
            "requires": "2.0.2-refsuite.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "ryft-android-2.0.2-refsuite.2.aar",
          "url": "ryft-android-2.0.2-refsuite.2.aar",
          "size": 810,
          "sha512": "e2a9568ca54ece13140312e95dd17572f9ebc721fcf86491dfac80f0104440bd347c6a1bf309ff7ec20eafb968960882cca2585316921f006df33fcd5535fe33",
          "sha256": "2c5ec3e2c05c7795aa6fa787105e8c8bbd00ac771fbcf58d1f2844ebf3bf5328",
          "sha1": "fc35a43d054c7c1d16865cca4cc63b2f694df76a",
          "md5": "17a087a01353be84b09d66649172aa8d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.refsuite.ryft",
          "module": "ryft-core",
          "version": {
            "requires": "2.0.2-refsuite.2"
          }
        },
        {
          "group": "com.refsuite.ryft",
          "module": "ryft-ui",
          "version": {
            "requires": "2.0.2-refsuite.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "ryft-android-2.0.2-refsuite.2.aar",
          "url": "ryft-android-2.0.2-refsuite.2.aar",
          "size": 810,
          "sha512": "e2a9568ca54ece13140312e95dd17572f9ebc721fcf86491dfac80f0104440bd347c6a1bf309ff7ec20eafb968960882cca2585316921f006df33fcd5535fe33",
          "sha256": "2c5ec3e2c05c7795aa6fa787105e8c8bbd00ac771fbcf58d1f2844ebf3bf5328",
          "sha1": "fc35a43d054c7c1d16865cca4cc63b2f694df76a",
          "md5": "17a087a01353be84b09d66649172aa8d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ryft-android-2.0.2-refsuite.2-sources.jar",
          "url": "ryft-android-2.0.2-refsuite.2-sources.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ryft-android-2.0.2-refsuite.2-javadoc.jar",
          "url": "ryft-android-2.0.2-refsuite.2-javadoc.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
